export {
  PermContactCalendar as AdminIcon,
  Security as ClubsIcon,
  Flag as CountryIcon,
  Storage as DatabaseIcon,
  Home as HomeIcon,
  Sports as MatchesIcon,
  Note as NotesIcon,
  Visibility as ObservationIcon,
  Assignment as OrdersIcon,
  DirectionsRun as PlayersIcon,
  AccountCircle as ProfileIcon,
  Assessment as ReportsIcon,
  Create as ReportTemplatesIcon,
  Settings as SettingsIcon,
  GroupWork as TeamsIcon,
  Person as UserDataIcon,
} from '@mui/icons-material'
